package com.curiosity.crypto.controller;
// Code Generated by Sidekick is for learning and experimentation purposes only.


import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HomeController {

    @GetMapping("/")
    public String home() {
        return "Hello World!";
    }

    @GetMapping("/api")
    public String homeApi() {
        return "Hello to API world!";
    }
}